apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passkey-auth.secretName" . }}
  labels:
    {{- include "passkey-auth.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ .Values.secrets.sessionSecret | b64enc | quote }}
